apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}-serving-tests
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Release.Name }}
data:
  serving-tests-cpu.json: |
{{ .Values.servingTestsJson | indent 4 }}
